### ISSUE TITLE
Get Energy Usage returns the wrong data

### ISSUE THREAD

**Issue by owaits** [cwakefie27/TapoConnect#4]
The method GetEnergyUsageAsync returns DeviceGetInfoResult which contains no information about the energy usage. It should return a json object that contains the correct energy usage data from the device.

**Comment by cwakefie27** [comment]
I don’t currently have a device that has this feature to test with. If you
would like to alter the code it should not be too difficult.

**Comment by owaits** [comment]
This appears to be fixed in this fork https://github.com/lcervo/TapoConnect but there is no pull request.

**Comment by cwakefie27** [comment]
I just pulled in that version. I have not tested it so please proceed knowing it is untested code. Thanks
