### ISSUE TITLE
TapoDeviceClient only tries the first protocol.

### ISSUE THREAD

**Issue by oznetmaster** [cwakefie27/TapoConnect#6]
https://github.com/cwakefie27/TapoConnect/blob/eb20fb9850ec57b445af912ce3f83d640dd4db53/src/TapoDeviceClient.cs#L55

This line catches only a single exception.  All other exceptions terminate the Login.  If the exception is in the first protocol, the second protocol is never tried.

**Comment by cwakefie27** [comment]
You are correct. I had no way of testing this on a light with the older firmware. The 3.2.0 version I was able to test and fix this issue. Thanks
